version: '3.9'
services:
  backend:
    build:
      dockerfile: ./Api/Dockerfile
      context: .
    ports:
      - "7161:7161"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:7161"
      ASPNETCORE_ENVIRONMENT: "Docker"
    volumes:
      - type: bind
        source: ./Api/dataSeed.db
        target: /App/dataSeed.db
  frontend:
    build: 
      dockerfile: ./Client/Dockerfile
      context: .
    ports:
      - "5161:5161"
    depends_on: 
      - backend
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5161"
      ASPNETCORE_ENVIRONMENT: "Docker"
